[project]
name = "ulpsych-programing-club"
version = "0.1.0"
description = "Materials to help accademic writers move to more modern tooling."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
