project:
  type: default  # You’re not building a website or book, so "default" is right

format: 
  revealjs:
    incremental: true
    theme: sky

jupyter:
  kernelspec:
    name: pss_2025
    display_name: "pss_2025"
    language: python

bibliography: references.bib
csl: apa.csl

