---
title: Week 2 - Getting to work
jupyter: python3
---


Welcome back to week 2 of python for SPSS users. Thank you for joining us again. This week we're going to start actually doing things in python, learning about string operations, methods, and functions. But first...

## Lets recap! (1/3)


Last week, we learned that one of the important things to do when you are learning and writing code is to use comments. Comments are pieces of information that we write in our Python code that is not interpreted by our computer. Insteads comments are used by programmers to label their code, structure their code into sections, describe what their code is doing, and to identify areas of misunderstanding. That way when other people come to read your code (or when you come back to read your code in 6 months wondering what the hell you were trying to do) they'll be in a much better position to understand what your code is doing. To write comments in Python, we use the '#' symbol. 


```{python}
#### Write a comment below with your name, the week of the workshop, and what you hope to achieve from taking part in this workshop

## Replace the following with your own comment
# Name: Ryan Donovan, 
# Week: 2, 
# Hope: To remove the plague of SPSS that has corrupted the minds of oh so many Psychologists 
```


## Lets recap! (2/3)

Last week, we learned about 3 basic python datatypes:

 1. Strings: This is the datatype for written language. You make one by simply enclosing text (alphanumberic caracters and punctuation) in either apostrophies or double quotes (depending on whats in the text)
 2. Ints: This is the datatype fot whole numbers, like 4, 230000, -1 etc. 
 3. Floats: This is the datatype for numbers with a decimal point, like .05, 2.4, -3.0 etc.

And we also learned about 2 basic data structures:
 1. Lists: A list is a collection of items enclosed in square brackets [] and seperated by commas
 2. Dicts: A dict is a collection of 'key:value' pairs enclosed in curly brackets {} seperated by commas. 

In the `code` cell below make 1 example of each of these datatypes, you can check each example by pressing the play button after making each example. 

```{python}
# Make a single quote string below

# Make a double quote strint below (include an apostrphie in the text)

# Make an int below

# Make a float below

# Take the strings, int and float you just made and put them in a list

# Now take those things and put them in a dict in the format {'string1':, 'string2':, 'int':, 'float':, 'list':}
```

Well done!! You remembered how to make each type of datatype, and you made a couple of data structures, you're practically an expert pythonista already. 

## Let's Recap! (3/3)
The last thing we covered last week was the python use of the term '**variable**'. 

In python, a variable is essentially just a label that contains a piece of information. At the most basic level this is useful becuase it allows us to keep track of something, and work with it, using very little code. 

Last weeks we started with the string `'Hello World!'` but lets imagine we have a long string

`"It’s not so much what we have in this life that matters. It’s what we do with what we have. – Mr. Rogers"`

If we had to type this out everytime we wanted to interact with it it would be really unwieldy, so giving this string a short label (assigning it to a variable) would make it much easier to work with.  

```{python}

my_variable = "It’s not so much what we have in this life that matters. It’s what we do with what we have. – Mr. Rogers" # note the = between the variable name and the string, and the underscore in the name

print(my_variable) # This tells the computer to write the variable out below this cell
```


Notice how instead of printing out 'my_variable' python prints out the data that is contained in the variable. 

Couple of things to note here:
 1. The variable name is made of alphabetic characters, not numbers or punctuation
 2. We use underscores to seperate parts of the variable name, this is similar to variable names in SPSS
 3. The equals sign (=) is what links the variable name to the data object

In the cell below, play around a little with making some variables of your own. Make a few different variables of different types with different labels. Run the cell (press play on the cell) after you've made each variable to see if the assignment has worked properly.

Oh also `# Don't forget to use comments` (seriously.... seriously).

```{python}
# Make a few variables in this cell, don't forget to run the cell after making each variable to make sure it works.
```

OK, thats enough recapping, it's time to actually start working with some data. 

Even though most people think about numbers when programming comes up, and indeed we most often work with numerical data in SPSS, we're going to start with strings. This allows us to demonstrate some really useful basic principles of python that apply to other datatypes, without giving people the excuse that they 'hate maths'. You can all write essays, which means you can all work with language. So let's work with language.

# Operations with Strings

Okay we lied to you. This next section will contain some information on numerical data to illustrate some important things about what we can do with strings in Python. Then we will focus exclusively on language, pinky-promise. 

When we are working with numbers, we are used to the idea that we can perform several type of operations on those numbers. By operation, I mean some process where we take in information (input) to spit out new information (output). For example, we can use addition to get the sum of two or more numbers: `5 + 2 = 7`; `3 + 4 + 5 = 12`. Or we could use multiplication to get the product of these numbers: `5 * 2 = 10`; `3 * 4 * 5 = 60`. Additionally, we perform operations like division or subtraction. 

When we work with text, however, we don't often think in terms of operations or of mechanical processes. For example, imagine you asked someone how to spell the word "Weird" and they said: "Okay so you start with a 'W', and then you add an 'e' to it to get 'We', and then you add 'i' to get 'Wei', and then you add 'r' to  'Wei' to get 'Weir', and then finally you add 'd' to 'Weir' to get Weird..... :)" You'd think they were weird (if not an outright moral degenerate), and you'd be right. Normally, when we use language, we use more intuitive processes (like sounding out how a word is spelt). But, in the magical world of Python, we can and often will perform operations on text (AKA strings). Two examples of string operations are "String Addition" and "String Multiplication"

## String 'Addition' (String Concantenation)

In python we can add two or more strings together: 

```{python}
## Execute the code below

print('hand' + 'bag')
print('bull' + 'dog')
print('counter' + 'clock' + 'wise')
```

This operation, adding two or more strings together, is called `String Concantenation`. Concantenation being the latin word for "gluing crap together" (no need to fact check this). 

You can see from the examples above, that concantenation (or string addition) takes whatever is inside one string and sticks it directly on to the end of the previous string with no space in between. This is in contrast to how addition works with numbers, where adding two or more numbers results in a seperate number. 

You can also perform string addition with string variables

```{python}
# Create two variables, one variable for your first name (label it first_name) and one variable for your last name (label it last_name), and then add those two variables together

# Variable 1


# Variable 2


#print(variable1 + variable 2)

```

As you can see, Python glues whatever was stored in the first_name variable directly onto the beginning of whatever was stored in the last_name variable. 

If we want to include a space between our two variables, there are two main approaches to achieving this

```{python}
## Approach 1. We can use a space either at the end of the first variable, or a space at the beginning of second variable, and them add the two variables together:

space_first_name = "Grampton " ## put a space between the end of the name and the quotation mark
no_space_last_name = "St.Rumpterfraple"
print(space_first_name + no_space_last_name)
```

```{python}

no_space_first_name = "Grampton"
space_last_name = " St.Rumpterfraple" ## put a space between the start of the name and the quotation mark

print(no_space_first_name + space_last_name)

```

This approach is fine if what you are printing is a once off (i.e., you are not using variables). 

If you are using variables, however, then the space will remain a part of our variable until we specifically change it. If we forget to do this, we can cause ourselves problems down the line (this will become clearer as the weeks go on).

```{python}

## Approach 2. A better approach is to add a string inbetween our two variables:

my_first_name = "Harry"
my_last_name = "Potter"

print(my_first_name + " " + my_last_name)

# The " " string adds a space between our two variables. 
```

```{python}
### Use approach 2 to print out your full name, using the two variables you created earlier, with a space in between your first and last name. 
```

An important thing to note about string addition, is that it works exclusively with strings. You cannot add a string to an int or a string to a float. 

```{python}
### Try adding a str to an int or to a float, notice the error message that pops up
```

## String Multiplication (String Replication)

You can also perform "string multiplication", an operation known as `string replication`. 

```{python}
print("a" * 3)
```

```{python}
print("do"*2) #like the bird
```

```{python}
print("Are we there yet? " * 5) #Like your annoying little brother or sister. NOTE: I am using a space here at the end as I am just printing the string once off, I am not using a variable
```

You can see in each case, that when we 'multiply' a string, we replicate it, and then add the replication onto to the end of our original string. You will also notice that, in contrast to string addition, you can combine strings and integers. Integers are used to specify the number of times you want to replicate the string. However, string replication does not work with floats. 

```{python}
lyrics = "Around the world, around the world\n" ## Do not worry about the \n for now, this is just a special character that tells Python to create a new line after the string

print(lyrics * 8) #Notice the "TypeError" message in the output. Have a read through it, and once you are ready, change the float 8.0 into an interval, and re-run the code. 

# There you have just printed out the first verse of Daft Punk's 1997 hit single "Around the World"! 
# You can change the 8 to 80 to print out the radio version of the song, 
# or you change it to 144 to print out the entire album version of the song. 
```

## String-Ception: Putting Strings Inside Other Strings

A common operation that you will use in Python is putting a string(s) variables inside other strings. Technically we could achieve this by using string concatenation

```{python}
my_first_name = "Harry"
my_last_name = "Potter"
subject = "Wizardry"
university = "Hogwarts"

print("Hi there, my name is " + my_first_name + " " + my_last_name + ". I studied " + subject + " at the University of " +  university + ".")
```

But in order to print out this sentence in a correct manner, we need to perform string concantenation (using the '+' operator) multiple times in order to:

I. To add the the string `"Hi there, my name is "` to the `my_first_name` variable

II. To add the `my_first_name` variable to the string `" "`

III. To add the string `" "` to the `my_last_name` variable

IV. To add the `my_last_name` variable to the string `". I studied "`

V. To add the string `". I studied "` to the `subject` variable

VI. To add the `subject` variable to the string `" at the University of "`

VII. To add the the string `" at the University of "` to the `university` variable

VIII. Finally, to add the `university` variable to the the string `"."` . 


This is a **collosal pain in the ass**. We are always likely to make small mistakes (maybe we forget to leave a space between variables, or forget to add a full-stop)


Instead of using the string concantenation operation here, a much handier approach is to use an `f-string operator`. `F-strings` are known as formatted strings (get it?), and they enable us to plug in our variables without the need to excessively worry about formatting. 

```{python}
print(f"Hi there, my name is {my_first_name} {my_last_name}. I studied {subject} at the University of {university}.")# We know Hogwarts isn't a university you massive nerd. 
```

We place a **f** at the start of our string, and then wherever we want to plug in one of our variables, we use a curly bracket {} to tell Python we are inserting a variable in here, and then we type the variable name inside the curly bracket. So much easier! 

In the cell below print out a sentence stating your first name, last name, subject, and university, using the f-string operator.  



```{python}
# Use your own variables you defined earlier for your first name and last name.


# Copy and paste the Subject and Variables variables from up above here. Change the values assigned to those variables




### Print your f-string

```

Now let's introduce another important operation that we can run on strings: **Indexing**. 


## Indexing
The index of a particular object is it's position in a collection of objects. That might seem like jargon (and in fairness it kind of is) but let's use a string as an example to clear that up. 

```
m = 'hello world'
```

You already know that a string is an object made of alphanumeric characters enclosed in either single or double quotes, so in general we think of a string as an object unto itself, but, we can also think as a string as a collection of individual characters, each character (including spaces) can also be thought of as an object (essentially, python can treat a `string` as a `list` of alphanumeric objects enclosed in quotes instead of square brackets). 

The variable `m` that we assigned just above is a string which is 11 characters long. Each of those characters has a position within the string and this position is identified with a number. You might think that in `m` the position of the first character ('h') would be 1, but python is what's called a '0-indexed language', this means that we start counting positions from 0 instead of 1, this is demonstrated in the table below. 


|index | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
|:-----|:--|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|--:|
|char  | h | e | l | l | o |   | w | o | r | l | d |

This is quite powerful because it allows us to do things like search *within* an object, or pick an object apart. Let's start with just picking out the first character ('h') in `m`, it's really easy. 

```{python}
m = 'hello world' #assining 'hello world' to the variable m

print(m[0])# Note the square brackets (like a list) and the int 0
```

The first line in the cell above you already know, we've just taken a `string` variable ('hello world') and given it the label (assigned it to the `variable`)   - `m`. 

The second line is the magic. 

Remember that `m` represents our string so python knows that we are working on that parituclar object. Immediately after `m` we open square brackets `[` (like we used when we were making a list) then we put in the `index position` (represented by a number, look back up at the table above) and then we closed the square brackets `]`. This is the basic `syntax` for finding an object in a collection of objects. 

[`syntax` basically referes to a pattern of language, so when we use `syntax` in the context of code we just mean the pattern of code that you use to do particular thing. Basically, learning to code is just learning the patterns of a particular language.]

So we can do the same thing with `lists`, and a very similar thing with `dicts` and full datasets (`DataFrames`, more on this in future sessions). 

lets take a list 

`beatles = ['John', 'Paul', 'George', 'Ringo']`

This list is indexed exactly the same way as `m`

|index | 0 | 1 | 2 | 3 |
|:-----|:-:|:-:|:-:|:-:|
|item  | 'John' | 'Paul' | 'George' | 'Ringo' |

So we can use exactly the same `syntax` to find out what is at a particular `index` in the list. 

```{python}
beatles = ['John', 'Paul', 'George', 'Ringo'] #creating the list, and assigning it the variable beatles

print(beatles[0])# getting the first object from the list beatles
```

In the cell below, make a string and a list, assign both to a variable and try using the `syntax` we've just spoken about to pick out one of the elements of each.

(again, don't forget to comment the code)

```{python}
# Make your string varible below, just one word, maybe 5 letters long since wordle is a thing

# Make your list varible below, put at least 5 items in your list, remember the can be ints, floats, strings, etc, so play around, or don't, I'm not your boss

# Try selecting the 3rd character in your string (remember we start counting from 0)

# Try selecting the 4th item in your list (again starting from 0)

# Try selecting the 2nd character from one of the strings in your list.
```

Well done, you just worked with indexes for the first time. Although examples above are pretty simple, they are the foundation of some pretty useful tools in python, again imagine you had a really long list, or a very long string (or a big dataset), you can use similar syntax to engage with single parts of that object, you can move them around or you can save them to a seperate variable...

```{python}
# run this cell and see if you can figure out what is going on, write in your own comments to explain the code (really look at the first line of code, you can go back up to see what m is if you need to)

j = m[-1]
k = beatles[2] 

print(j)
print(k)
```

We did a couple of things there, and one is kind of sneaky (sorry/not sorry). 

At the simplest level, we used our `indexing syntax` to extract a character from a string and *store it as a new variable*, then we used the same `syntax` to save 1 of the elements from our list sperately. Then we just got the computer to print out each of those new variables. It's worth noting that we haven't acctually changed the list or string, when we say we've 'extracted' a part of them we don't mean that we have literally just pulled them out, we just mean we've selected those bits of information and given us a way to access them easily, but the original items are still intact, run the cell below to see. 

```{python}
print(m)
print(beatles)
```

So the original object is undisturbed when we do this, but we can capture part of it, work with it, and then if we want to we can update the original object again (don't worry about updating for now, but it can be done.)

...

So....did you spot the sneaky thing we did when we created the variable `j`? 

**Didja?**

We used `-1` as the index to get the last letter of `'hello world'`... 'd'. This is called negative indexing and it allows us to get the last (or second last and so on) item from a list or string *without having to know how many items are in the list*.

**Awesome**, you probably think it's not, but believe me... it is, it inspires awe. 

OK so, we know that `m` is 11 characters long (remember that the space is also a character) so we could just use 

`m[10] # rememer that we count from 0` 

to get the last character, but if we don't know the length of the object (or can't be bothered to remember how long it is, lets be real here) we can use

`m[-1] # using negative indexing instead of the 'actual' index postion` 

In the cell below, play around with `indexing`, positive (starting from 0) and negative (starting from minus 1) using the list and string variables you made earlier. You don't have to make them again, the `code cells` talk to each other so just make sure you've run all the cells above (start with the first one and make your way down in order). 

```{python}
# use this cell to play around with indexing, you can run the cell everytime you make a change
# you might need to use 'print()' if you want to display a result when the cell runs
# don't forget to comment your code



```

Boom, you just used `indexing` to play around with lists and strings. You absolute **unit**. When it comes to indexing disctionaries it's a little more complex, but not a lot. Take a look at the code below for an example. 

```{python}
d = {'name':'Andrea','age':32, 'course': 'MA'} # a simple dict containing some demographic info
d['name'] # using the 'key' to access the value in the dictionary
```

In the case of a `dict` the `syntax` is really similar, 'cept we use the `key` of the `key:value` pair instead of a numerical index. 

**The key 'unlocks' the value...**

Sorry, we probably didn't need to put that in bold... that's just what helped us remember it. 

This gets cool when have more complex `dicts` (like dataset)

```{python}
# lets make a dict of participants (each participant is their own dict)
participants =  {'aa01':{'age':32, 'gender':'male', 'condition':'Control', 'score':7},'aa02':{'age':50, 'gender':'female', 'condition':'Experimental', 'score':4}}


participants['aa01']['score']# getting participant aa01's score
```

As you can see up above, `participants` is a `dict` of `dicts` and we have basically stacked `keys` (with each individivual `key` enclosed in square brackts) to drill down into the dict to pull out a specific value. In the cell below, try to get the gender and age of participant 'aa02'

```{python}
# extract the gender on the next line


# extract the age on the next line

```

This was just an introduction to indexing, and we'll play around with it more when we start working with full datasets, but if you want to learn more about it you can check out [this tutorial](https://pythonguides.com/indexing-and-slicing-in-python/), it will give you more examples, and also will introduce you to something called `slicing`. We'll cover `slicing` ourselves later, but you should feel free to dive into it yourselves. Don't forget that you have a spare jupyter notebook made in week one that you can play around in if you want (and we strongly encourage it). For now we're going to move on to... 

# Functions
Before we get into what functions are, we need to appologise, for you see, we tricked you. We tricked you into useing functions without telling you... and we're deeply sorry (cough)... 

`print('Hello world')`

That line of `code` tells the computer to write out the `string` 'Hello world'. Getting the computer to write something out actually requires a lot of code, but thanks to `functions` we can 'compress' all that code, all its functionality, into a simple-to-type statement *followed by a pair of brackets*. You've also seen another function:

`type('Hello world')`

This line tells python to find the datatype of the object between the brackets. Again, theres a lot of code 'hidden' behind `type()` but we don't need to worry about that now, right now we just want to pay attention to the `syntax` for both of those functions: 


`function_name(thing to run the function on, also called an argument)`

we start by typing the name of the function (print, or type in the examples we've used so far), then we open brackets, then we enter the object we want the function to work on, then we close the brackets. We have laid out some `code cells` below that demonstrates this, run each cell and write in some comments explaining whats happening in each line. 

```{python}
a = 'This is a string'#
b = 10#
c = ['Sarah', 'Navid', 'Robert', 'Noura']#
```

```{python}
print(a)#
```

```{python}
type(b)#
```

```{python}
# note this cell!
print(type(c[1]))#
```

```{python}
d = len(c)# len() is the function that tells us the length of an object. 
print(d)# 
```

In the above cells, we `defined` a few `variables` and `called` a few `functions` on them. In the 3rd cell we actually `called` a `function` *within* another `function`, and in the 4th one, we used a `function` to *create* a `variable`, all with really small amounts of typing on our part. This should demonstrate that functions are really useful. Let's look at how `functions` are made (the `syntax` of `defining a function`)

## Defining our own funtions
Lets imagine that we want to have the computer take any number and multiply it by 42 (get it?) and then print out the result. We know that this is a simple example, but go stick with us here. 

if we were only doing it once we would just write

```
#lets just use 3 for this example
print(3*42)
```

However, if we want to have the ability to do this often, we might want to make a function that does this for us...

```{python}
def my_func(i): # def is short for define, i is a placeholder variable, not the colon after the brackets
    print(i*42)# note the indentation, indentation is really important, we indent using 'tab' (or 4 spaces, but don't do that)
```

OK, so we hear you asking

*What, in the name of mercy, did we just do?*

And that's a good question, but there's no need to get upset. Let's walk through each part of the `syntax`.

 1. When making a function we start on a newline with the term `def` which is short for 'define' (in technical terms we're 'defining' a function). 
 2. Then we type the name for our functions (in that example we just called it `my_func`, using underscore instead of spaces).
 3. Then we open brackets, put in a placeholder variable (`i` in this case, but it could be `x` or `banana`), then close the brackets.
 4. Then we finish that line with a colon (:)
 5. Then we go to a newline
 6. Then we `indent` the line with either a 'tab' or 4 spaces (don't use 4 spaces, it'll work but just... don't be that guy)
 7. Then we can start putting in the functionality

Indentaion is a whole thing in python, it has to do with something called `scope` and we'll cover it more in more detail in later sessions, but for right now just know that in simple functions, every new line under the `def` line (after the colon) starts with an indentation. Because we're working in VScode, and we've told VScode that we're working in python, it will *usually* put the indentation in for you, but there will be times when you need to manage the indentation yourself. 

In the cell below, we've defined a function with incorrect indentation, run the cell first, read the error, then go back and fix the indentation (and for the love of God, use tab not 4-spaces)

```{python}
def new_function(): # we're not putting a placeholder variable in this cause we don't need it
print('This')# We're splitting the functionality up into multiple lines
print('Function')
print('Works')#
```

You'll notice that before we fix the cell up above we get an error (called a `traceback` in python language, can you think of why?) but once we fix the indentation we get no out put from the cell, this is because we just `defined` the `function`, we never `called` it. Calling a function is easy:

```{python}
my_func(12)#calling the 'my_func()' function to multiple 12 by 42
```

This is exactly the same as using the `print()` and `type()` functions in the earlier examples. 

OK, now for the final excercise of this week we want you to `define` a `function` that uses a little bit of everything we've covered this week. 

This function should take a string as an `argument` (the bit between the brackets) and then, using `f-strings` and `indexing` prints out something like

`This is my string: (string); and its last letter is (last letter)`

All the `syntax` you need is in this notebook, just take your time and think about the 'order' that you want things to happen in, don't forget to comment your code and don't forget to call the function once it's working. 


```{python}
# define a function that takes a string as an argument and prints out an 'f-string' containing the whole string and the last character




# call your function here
```

OK, well done. Some of you might have found that easy, some may have found it more challenging, and you might need to practice those things a few times, but remember, you can always read back through the notebooks, you can also look for tutorials online, and you can also ask for help (from eachother, us, or the internets)

Next week we'll talk about such amazing topics as `methods` (another word that doesn't mean what you think it means), `modules`(there's another) and the standard library, and `virtualenvs`. If you want to you can go look these up now, or you can wait for us to bring you through them. 

Thanks a lot for sticking with us this week, and make sure you run your work by us before you go. 


Best wishes, 

Ryan and Kev 

